# Component list

components:
  header:
    class: App\MobileEntry\Component\Header\HeaderComponent

  footer:
    class: App\MobileEntry\Component\Footer\FooterComponent

  slider:
    class: App\MobileEntry\Component\Slider\SliderComponent
