# Component list

modules:
  session:
    class: App\MobileEntry\Module\Session\SessionModule
  product_integration:
    class: App\MobileEntry\Module\ProductIntegration\ProductIntegrationModule
  owsports_integration:
    class: App\MobileEntry\Module\ProductIntegration\OWSports\OwsportsIntegrationModule

components:
  header:
    class: App\MobileEntry\Component\Header\HeaderComponent
  
  header_menu:
    class: App\MobileEntry\Component\Header\Menu\MenuComponent
    parent: header

  footer:
    class: App\MobileEntry\Component\Footer\FooterComponent

  profiler:
    class: App\MobileEntry\Component\Profiler\ProfilerComponent

  basic:
    class: App\MobileEntry\Component\Main\Basic\BasicComponent

  node:
    class: App\MobileEntry\Component\Node\NodeComponent

  node_blog:
    class: App\MobileEntry\Component\Node\Blog\BlogComponent

  home:
    class: App\MobileEntry\Component\Main\Home\HomeComponent

  home_slider:
    class: App\MobileEntry\Component\Main\Home\Slider\SliderComponent
    parent: home

  home_products:
    class: App\MobileEntry\Component\Main\Home\Products\ProductsComponent
    parent: home

  balance:
    class: App\MobileEntry\Component\Header\Balance\BalanceComponent
    parent: header

  announcement:
    class: App\MobileEntry\Component\Announcement\AnnouncementComponent

  language:
    class: App\MobileEntry\Component\Language\LanguageComponent

  push_notification:
    class: App\MobileEntry\Component\PushNotification\PushNotificationComponent
