# Define components
components:
  access_denied:
    class: App\MobileEntry\Component\Main\AccessDenied\AccessDeniedComponent

  header:
    class: App\MobileEntry\Component\Header\HeaderComponent

  header_login:
    class: App\MobileEntry\Component\Header\Login\LoginComponent
    parent: header
  
  menu:
    class: App\MobileEntry\Component\Menu\MenuComponent

  meta:
    class: App\MobileEntry\Component\Meta\MetaComponent

  footer:
    class: App\MobileEntry\Component\Footer\FooterComponent

  profiler:
    class: App\MobileEntry\Component\Profiler\ProfilerComponent

  basic:
    class: App\MobileEntry\Component\Main\Basic\BasicComponent

  node:
    class: App\MobileEntry\Component\Node\NodeComponent

  node_blog:
    class: App\MobileEntry\Component\Node\Blog\BlogComponent
    parent: node

  node_promotions:
    class: App\MobileEntry\Component\Node\Promotions\PromotionsComponent
    parent: node

  lobby:
    class: App\MobileEntry\Component\Main\Lobby\LobbyComponent

  lobby_slider:
    class: App\MobileEntry\Component\Main\Lobby\Slider\SliderComponent
    parent: lobby

  lobby_content:
    class: App\MobileEntry\Component\Main\Lobby\Home\HomeComponent
    parent: lobby

  home_products:
    class: App\MobileEntry\Component\Main\Lobby\Home\Products\ProductsComponent
    parent: lobby_content

  home_download:
    class: App\MobileEntry\Component\Main\Lobby\Home\Download\DownloadComponent
    parent: lobby_content

  games_lobby:
    class: App\MobileEntry\Component\Main\Lobby\GamesLobby\GamesLobbyComponent
    parent: lobby

  live_dealer_lobby:
    class: App\MobileEntry\Component\Main\Lobby\LiveDealerLobby\LiveDealerLobbyComponent
    parent: lobby

  casino_lobby:
    class: App\MobileEntry\Component\Main\Lobby\CasinoLobby\CasinoLobbyComponent
    parent: lobby

  casino_gold_lobby:
    class: App\MobileEntry\Component\Main\Lobby\CasinoGoldLobby\CasinoGoldLobbyComponent
    parent: lobby

  lottery_lobby:
    class: App\MobileEntry\Component\Main\Lobby\LotteryLobby\LotteryLobbyComponent
    parent: lobby

  announcement:
    class: App\MobileEntry\Component\Announcement\AnnouncementComponent

  language:
    class: App\MobileEntry\Component\Language\LanguageComponent

  push_notification:
    class: App\MobileEntry\Component\PushNotification\PushNotificationComponent

  casino_option:
    class: App\MobileEntry\Component\CasinoOption\CasinoOptionComponent

  promotions:
    class: App\MobileEntry\Component\Main\Promotions\PromotionsComponent

  cant_login:
    class: App\MobileEntry\Component\Main\CantLogin\CantLoginComponent

  cant_login_forgot_password:
    class: App\MobileEntry\Component\Main\CantLogin\ForgotPassword\ForgotPasswordComponent
    parent: cant_login

  cant_login_forgot_username:
    class: App\MobileEntry\Component\Main\CantLogin\ForgotUsername\ForgotUsernameComponent
    parent: cant_login

  cant_login_reset_password:
    class: App\MobileEntry\Component\Main\CantLogin\ResetPassword\ResetPasswordComponent
    parent: cant_login

  my_account:
    class: App\MobileEntry\Component\Main\MyAccount\MyAccountComponent
    headers:
      Cache-Control: no-cache, no-store, must-revalidate

  profile:
    class: App\MobileEntry\Component\Main\MyAccount\Profile\ProfileComponent
    parent: my_account

  profile_verify_password:
    class: App\MobileEntry\Component\Main\MyAccount\Profile\VerifyPassword\VerifyPasswordComponent
    parent: profile

  change_password:
    class: App\MobileEntry\Component\Main\MyAccount\ChangePassword\ChangePasswordComponent
    parent: my_account

  seo:
    class: App\MobileEntry\Component\SEO\SEOComponent

  marketing:
    class: App\MobileEntry\Component\Marketing\MarketingComponent

  backtotop:
    class: App\MobileEntry\Component\Backtotop\BacktotopComponent

  pwa_home_screen:
    class: App\MobileEntry\Component\PWA\PWAHomeScreenComponent

  cookie_notification:
    class: App\MobileEntry\Component\CookieNotif\CookieNotifComponent

  game_loader:
    class: App\MobileEntry\Component\GameLoader\GameLoaderComponent

# Define modules
modules:
  session:
    class: App\MobileEntry\Module\Session\SessionModule

  avaya:
    class: App\MobileEntry\Module\Avaya\AvayaModule

  balance:
    class: App\MobileEntry\Module\Balance\BalanceModule

  tracking:
    class: App\MobileEntry\Module\Tracking\TrackingModule

  product_integration:
    class: App\MobileEntry\Module\ProductIntegration\ProductIntegrationModule

  generic_integration:
    class: App\MobileEntry\Module\ProductIntegration\Generic\GenericIntegrationModule

  owsports_integration:
    class: App\MobileEntry\Module\ProductIntegration\OWSports\OWSportsIntegrationModule

  als_integration:
    class: App\MobileEntry\Module\ProductIntegration\ALS\ALSIntegrationModule

  game_integration:
    class: App\MobileEntry\Module\GameIntegration\GameIntegrationModule

  casino_integration:
    class: App\MobileEntry\Module\ProductIntegration\Casino\CasinoIntegrationModule

  pas_integration:
    class: App\MobileEntry\Module\GameIntegration\PAS\PASModule

  microgaming_integration:
    class: App\MobileEntry\Module\GameIntegration\MicroGaming\MicroGamingModule

  gold_deluxe_integration:
    class: App\MobileEntry\Module\GameIntegration\GoldDeluxe\GoldDeluxeModule

  voidbridge_integration:
    class: App\MobileEntry\Module\GameIntegration\Voidbridge\VoidbridgeModule

  cq9_integration:
    class: App\MobileEntry\Module\GameIntegration\CQ9\CQ9Module

  solidgaming_integration:
    class: App\MobileEntry\Module\GameIntegration\SolidGaming\SolidGamingModule

  skywind_integration:
    class: App\MobileEntry\Module\GameIntegration\Skywind\SkywindModule

  flowgaming_integration:
    class: App\MobileEntry\Module\GameIntegration\FlowGaming\FlowGamingModule

  sagaming_integration:
    class: App\MobileEntry\Module\GameIntegration\SAGaming\SAGamingModule

  pgsoft_integration:
    class: App\MobileEntry\Module\GameIntegration\PGSoft\PGSoftModule

  asiagaming_integration:
    class: App\MobileEntry\Module\GameIntegration\AsiaGaming\AsiaGamingModule

  rubyplay_integration:
    class: App\MobileEntry\Module\GameIntegration\RubyPlay\RubyPlayModule

  evolution_gaming_integration:
    class: App\MobileEntry\Module\GameIntegration\EvolutionGaming\EvolutionGamingModule

  ebet_integration:
    class: App\MobileEntry\Module\GameIntegration\EBet\EBetModule

  gpi_integration:
    class: App\MobileEntry\Module\GameIntegration\GPI\GPIModule

  login_redirect:
    class: App\MobileEntry\Module\LoginRedirect\LoginRedirectModule

  exchange_integration:
    class: App\MobileEntry\Module\ProductIntegration\Exchange\ExchangeIntegrationModule

  games_integration:
    class: App\MobileEntry\Module\ProductIntegration\Games\GamesIntegrationModule
  
  live_dealer_integration:
    class: App\MobileEntry\Module\ProductIntegration\LiveDealer\LiveDealerIntegrationModule

