# Subscribers
# 
# Under each event, you can have the following
# - arguments The array of argument to accept
# - hooks These are the classes that will subscribe to this event
subscribers:
  login_success:
    arguments: [username, password]
    hooks:
      - App\Handlers\Login\LegacyAuthentication
      - App\MobileEntry\Handlers\Login\Accounts
  logout:
    hooks:
      - App\MobileEntry\Handlers\Logout\DSBLogout
      - App\MobileEntry\Handlers\Logout\Accounts
