middlewares:
  request:
    slashes: App\Middleware\Request\Slashes
    page_cache: App\MobileEntry\Middleware\ResponseCache
    languages: App\Middleware\Request\Languages
    bootstrap: App\Middleware\Request\Bootstrap
    components: App\Plugins\ComponentWidget\Middlewares\ComponentWidgetInit
    legacy_auth: App\Middleware\Request\LegacyAuthentication
    session: App\Middleware\Request\Session

  response:
    token: App\Middleware\Response\Token
    components: App\Plugins\ComponentWidget\Middlewares\ComponentWidgetResponse
    page_cache: App\MobileEntry\Middleware\ResponseCache
    headers: App\Middleware\Response\Headers
    vary: App\MobileEntry\Middleware\Vary
    lazy_token: App\Middleware\Response\LazyToken
    profiler: App\MobileEntry\Component\Profiler\ProfilerMiddleware

  cache:
    bootstrap: App\Middleware\Cache\Bootstrap
    components: App\Plugins\ComponentWidget\Middlewares\ComponentWidgetResponseCache
    headers: App\Middleware\Response\Headers
    vary: App\MobileEntry\Middleware\Vary
    lazy_replacement: App\Middleware\Cache\LazyReplacement
    profiler: App\MobileEntry\Component\Profiler\ProfilerMiddleware
