middlewares:
  request:
    slashes: App\Middleware\Request\Slashes
    languages: App\Middleware\Request\Languages
    bootstrap: App\Middleware\Request\Bootstrap
    legacy_auth: App\Middleware\Request\LegacyAuthentication
    session: App\Middleware\Request\Session

  response:
    token: App\Middleware\Response\Token
    lazy_token: App\Middleware\Response\LazyToken
