middlewares:
  request:
    cookie_authentication: App\Middleware\Request\CookieAuthentication
    slashes: App\Middleware\Request\Slashes
    case_insensitive: App\Middleware\Request\CaseInsensitiveRoute
    page_cache: App\MobileEntry\Middleware\ResponseCache
    languages: App\Middleware\Request\Languages
    bootstrap: App\Middleware\Request\Bootstrap
    components: App\Plugins\ComponentWidget\Middlewares\ComponentWidgetInit
    legacy_auth: App\Middleware\Request\LegacyAuthentication
    session: App\Middleware\Request\Session

  response:
    ucp: App\MobileEntry\Middleware\UnsupportedCurrency
    token: App\Middleware\Response\Token
    components: App\Plugins\ComponentWidget\Middlewares\ComponentWidgetResponse
    page_cache: App\MobileEntry\Middleware\ResponseCache
    headers: App\Middleware\Response\Headers
    lazy_token: App\Middleware\Response\LazyToken
    clean_parameters: App\MobileEntry\Middleware\CleanParameters
    player_matrix: App\MobileEntry\Middleware\PlayerMatrix
    # profiler: App\MobileEntry\Component\Profiler\ProfilerMiddleware

  cache:
    bootstrap: App\Middleware\Cache\Bootstrap
    components: App\Plugins\ComponentWidget\Middlewares\ComponentWidgetResponseCache
    headers: App\Middleware\Response\Headers
    lazy_replacement: App\Middleware\Cache\LazyReplacement
    # profiler: App\MobileEntry\Component\Profiler\ProfilerMiddleware
