routes:
    /:
        method: GET
        action: App\MobileEntry\Controller\HomeController:view
        components:
            main: home
        headers:
            Cache-Control: public, max-age=1800
        page_cache:
            enabled: true
            expires: 1800

    /login:
        method: GET
        action: App\MobileEntry\Controller\HomeController:view
        components:
            main: home
        headers:
            Cache-Control: public, max-age=300
        page_cache:
            enabled: true
            expires: 1800

    /logout:
        method: GET
        action: App\MobileEntry\Controller\LogoutController:view
        headers:
            Cache-Control: no-cache, no-store, must-revalidate

    /promotions:
        method: GET
        action: App\MobileEntry\Controller\PromotionsController:view
        components:
            main: promotions
        headers:
            Cache-Control: public, max-age=900
        page_cache:
            enabled: true
            expires: 1800

    /change-password:
        method: GET
        action: App\MobileEntry\Controller\ChangePasswordController:view
        components:
          main: change_password

    # Definition of component controllers for cache control

    /api/plugins/component/route/promotions/promotions:
        method: ANY
        action: App\Plugins\ComponentWidget\ComponentWidgetController:routeStatic
        headers:
            Cache-Control: private, max-age=300
        page_cache:
            enabled: true
            expires: 1800

    /api/plugins/component/route/header/logout:
        method: ANY
        action: App\Plugins\ComponentWidget\ComponentWidgetController:routeStatic
        headers:
            Cache-Control: no-cache, no-store, must-revalidate

    # Standard component controllers

    /api/plugins/component/route/{id}/{method}:
        method: ANY
        action: App\Plugins\ComponentWidget\ComponentWidgetController:route
        headers:
            Cache-Control: no-cache, no-store, must-revalidate

    /api/plugins/module/route/{id}/{method}:
        method: ANY
        action: App\Plugins\ComponentWidget\ComponentWidgetController:module
        headers:
            Cache-Control: no-cache, no-store, must-revalidate

    /api/plugins/module:
        method: ANY
        action: App\Plugins\ComponentWidget\ComponentWidgetController:moduleList
        headers:
            Cache-Control: no-cache, no-store, must-revalidate

    /*.*:
        method: ANY
        action: App\MobileEntry\Controller\NodeController:view
        components:
            main: node
        headers:
            Cache-Control: public, max-age=300
        page_cache:
            enabled: true
            expires: 1800
