routes:
    /:
        method: GET
        action: App\MobileEntry\Controller\HomeController:view
        components:
          main: home

    /debug:
        method: GET
        action: App\Controller\DefaultController:debug

    /about:
        method: GET
        action: App\MobileEntry\Controller\AboutController:view
        components:
          main: basic

    /login:
        method: GET
        action: App\MobileEntry\Controller\HomeController:view
        components:
          main: authenticate

    /promotions:
        method: GET
        action: App\MobileEntry\Controller\PromotionsController:view
        components:
         main: promotions

    /api/plugins/component/route/{id}/{method}:
        method: ANY
        action: App\Plugins\ComponentWidget\ComponentWidgetController:route

    /api/plugins/module/route/{id}/{method}:
        method: ANY
        action: App\Plugins\ComponentWidget\ComponentWidgetController:module

    /*.*:
        method: ANY
        action: App\MobileEntry\Controller\NodeController:view
        components:
          main: node
