routes:
    /:
        method: GET
        action: App\MobileEntry\Controller\HomeController:view
        components:
            main: home
        headers:
            Cache-Control: no-cache, no-store, must-revalidate
        page_cache:
            enabled: true
            expires: 1800

    /debug:
        method: GET
        action: App\Controller\DefaultController:debug

    /login:
        method: GET
        action: App\MobileEntry\Controller\HomeController:view
        components:
            main: home
        headers:
            Cache-Control: no-cache, no-store, must-revalidate
        page_cache:
            enabled: true
            expires: 1800

    /logout:
        method: GET
        action: App\MobileEntry\Controller\LogoutController:view
        headers:
            Cache-Control: no-cache, no-store, must-revalidate

    /promotions:
        method: GET
        action: App\MobileEntry\Controller\PromotionsController:view
        components:
            main: promotions
        headers:
            Cache-Control: no-cache, no-store, must-revalidate
        page_cache:
            enabled: true
            expires: 1800


    # Definition of component controllers for cache control

    /api/plugins/component/route/promotions/promotions:
        method: ANY
        action: App\Plugins\ComponentWidget\ComponentWidgetController:routeStatic
        headers:
            Cache-Control: private, max-age=300
        page_cache:
            enabled: true
            expires: 1800


    # Standard component controllers

    /api/plugins/component/route/{id}/{method}:
        method: ANY
        action: App\Plugins\ComponentWidget\ComponentWidgetController:route

    /api/plugins/module/route/{id}/{method}:
        method: ANY
        action: App\Plugins\ComponentWidget\ComponentWidgetController:module

    /*.*:
        method: ANY
        action: App\MobileEntry\Controller\NodeController:view
        components:
            main: node
        headers:
            Cache-Control: no-cache, no-store, must-revalidate
        page_cache:
            enabled: true
            expires: 1800
