routes:
    /:
        method: GET
        action: App\MobileEntry\Controller\HomeController:home
        components:
          main: home

    /api/plugins/component/route/{id}/{method}:
        method: ANY
        action: App\Plugins\ComponentWidget\ComponentWidgetController:route

    /*.*:
        method: ANY
        action: App\MobileEntry\Controller\NodeController:viewNodeByType
