# Define token extensions herre
# Token extensions are classes that extend the token manager by modifying
# the list of available tokens
extensions:
  - App\Extensions\Token\DomainTokens

lazy:
  - tracking
  - tracking.creferer
  - tracking.token

# Define tokens here
# Key value pair of token key and token class
tokens:
  # User
  auth.token: App\Token\AuthToken
  auth.credentials: App\Token\AuthCredentials
  username: App\Token\Username
  cashier: App\Token\CashierToken

  # Language
  lang: App\Token\Language

  legacy.credentials: App\Token\LegacyToken
  credentials.params: App\Token\CredentialsToken
  tracking: App\Token\TrackingToken
  tracking.creferer: App\Token\TrackingCrefererToken

  # Special Tokens
  legacy.revamp.token: App\Token\LegacyRevampToken
