export class  ProductLanguage {
    private supportedLanguage = {
        "casino": [
            "en",
            "sc",
            "th",
            "vn",
            "id",
            "kr",
            "in",
            "pt",
            "es",
        ],
        "sports" : [
            "en",
            "eu",
            "sc",
            "ch",
            "th",
            "vn",
            "id",
            "jp",
            "kr",
            "in",
            "gr",
            "pl",
        ],
        "sports-df" : [
            "en",
            "eu",
            "sc",
            "ch",
            "th",
            "vn",
            "id",
            "jp",
            "kr",
            "in",
            "gr",
            "pl",
            "pt",
            "es",
        ],
        "lottery" : [
            "en",
            "sc",
            "th",
            "vn",
            "id",
            "kr",
        ],
        "live-dealer" : [
            "en",
            "sc",
            "th",
            "vn",
            "id",
            "kr",
            "in",
        ],
        "games" : [
            "en",
            "sc",
            "th",
            "vn",
            "id",
            "kr",
            "pt",
            "es",
        ],
        "exchange" : [
            "in",
        ],
        "arcade" : [
            "en",
            "sc",
            "th",
            "vn",
            "id",
            "kr",
            "pt",
            "es",
        ],
        "virtual-sports" : [
            "en",
            "sc",
            "th",
            "vn",
            "id",
            "jp",
            "kr",
            "pt",
            "es",
        ],
    };

    getSupportedLanguage() {
        return this.supportedLanguage;
    }
}
